# Artificial Neural Network

## Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Importing the dataset

In [2]:
dataset = pd.read_csv('data.csv')
del dataset["id"]
del dataset["age_days"]
print(dataset.head())

#redundant data variables
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

X.reshape(-1,1)

X.astype('float32')
X = X / 255.0

    age_year  gender  height  weight  ap_hi  ...  gluc  smoke  alco  active  cardio
0  50.391781       2     168    62.0    110  ...     1      0     0       1       0
1  55.419178       1     156    85.0    140  ...     1      0     0       1       1
2  51.663014       1     165    64.0    130  ...     1      0     0       0       1
3  48.282192       2     169    82.0    150  ...     1      0     0       1       1
4  47.873973       1     156    56.0    100  ...     1      0     0       0       0

[5 rows x 12 columns]


##Visualize the data

In [3]:
#sns.pairplot(dataset)      #using seaborn lib to visualize data

## Splitting the dataset into the Training set and Test set

In [4]:
#spliting the data
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 1)

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

#scaling the data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)



##Feature Scaling

##Building the model

In [5]:
import tensorflow.keras
from keras.models import Sequential
from keras.layers import Dense, MaxPooling2D, Flatten, Dropout, BatchNormalization, Conv2D
from sklearn.preprocessing import MinMaxScaler
from keras.optimizers import RMSprop, SGD, Adam


In [6]:
#building different layers for the model
model = Sequential()    #creating a sequential model
model.add(Dense(32, activation = "relu",input_shape=(52380, 11)) )
model.add(Dense(32, activation='relu'))    
model.add(Dense(100, activation='relu'))              
model.add(Dense(2, activation='relu')) 
                 
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 52380, 32)         384       
_________________________________________________________________
dense_1 (Dense)              (None, 52380, 32)         1056      
_________________________________________________________________
dense_2 (Dense)              (None, 52380, 100)        3300      
_________________________________________________________________
dense_3 (Dense)              (None, 52380, 2)          202       
Total params: 4,942
Trainable params: 4,942
Non-trainable params: 0
_________________________________________________________________


In [7]:
#building the model
opt = Adam(lr=0.01)
model.compile(optimizer=opt, loss='mean_squared_error',metrics=['accuracy'])  #using adam optimizer to update the 
                                                                              #weights and mean squared error is to be reduced

In [ ]:
#fitting the model
epochs_hist = model.fit(X_train, y_train, epochs=100, batch_size=64, validation_split=0.2)
#the traing of the model is done for 100 iteration 

Evaluation of the model

In [10]:
print(epochs_hist.history.keys())

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])


Evaaluating the model on test data

Generating Predictions

In [13]:
y_pred = model.predict(X_test)
y_pred = y_pred.round()
print(y_pred)
y_pred = np.argmax(y_pred, axis=1)
print(y_test)
y_test = np.argmax(y_test, axis=1)

[[0. 1.]
 [0. 1.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [0. 1.]]
[[1. 0.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [0. 1.]]


Evaluating the model

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
#print("Precision:",metrics.precision_score(y_test, y_pred))
#print("Recall:",metrics.recall_score(y_test, y_pred))

[[7822 2660]
 [2935 7535]]


0.7329610538373424

In [15]:
#per label classification
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      0.75      0.74     10482
           1       0.74      0.72      0.73     10470

    accuracy                           0.73     20952
   macro avg       0.73      0.73      0.73     20952
weighted avg       0.73      0.73      0.73     20952

